# Generated by Django 3.1.3 on 2022-06-18 16:05




from django.conf import settings

from django.db import migrations, models

import django.db.models.deletion







class Migration(migrations.Migration):




    initial = True




    dependencies = [

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]




    operations = [

        migrations.CreateModel(

            name='Profile',

            fields=[

                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('photo', models.ImageField(default='profile.jpg', upload_to='profiles')),

                ('Bio', models.CharField(max_length=30)),

                ('datecreated', models.DateField(auto_now_add=True)),

                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),

            ],

        ),

        migrations.CreateModel(

            name='Projects',

            fields=[

                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('title', models.TextField(max_length=30)),

                ('image', models.ImageField(blank=True, upload_to='images/')),

                ('link', models.URLField()),

                ('description', models.TextField(max_length=300)),

                ('datecreated', models.DateField(auto_now_add=True)),

                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='projects.profile')),

            ],

        ),

    ]